default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        add_data_job:
          class: AddDataJob
          schedule: every second
  # workers の設定も記述しないと job が queue に溜まるだけになる
  workers:
    - queues: "*"
      threads: 3
      processes: 1
      polling_interval: 0.1

development:
 <<: *default
#
# test:
#  <<: *default
#
# production:
#  <<: *default
